### ISSUE TITLE
openSkies CRAN package

### ISSUE THREAD

**Issue by Rafael-Ayala** [atmdata/atmdata.github.io#3]
Hi,

We just found out about this nice collection of aviation resources! 

We are the developers of the CRAN package "openSkies", designed to be the basis for the retrieval, analysis and visualization of aviation data in R. We just pushed a new update including many novel features, including an ADSB decoder.

We think the package might be appropriate for inclusion under the Tools section ! Here is the link to the release version (on CRAN) https://cran.rstudio.com/web/packages/openSkies/index.html . And here is the development version on GitHub https://github.com/Rafael-Ayala/openSkies

Thanks a lot in advance!

**Comment by xoolive** [comment]
Hello Rafael, that's great news! @espinielli will be excited about it!

Would you mind making a pull request to edit the website were you find appropriate? The file for the tools section is `_pages/tools.md`. Please feel free to copy-paste the template of other tools and write the description that best describes your tool!

Once the PR is accepted (within hours), your content will be immediately online.

**Comment by Rafael-Ayala** [comment]
Hello Xavier,

Great, thanks a lot! I have now done the pull request, adding a description of our tool at the end of _pages/tools.md with the template of the other tools!

Best wishes,

Rafa

**Comment by espinielli** [comment]
I'll surely have a look!
Thanks for letting us know.
